name: C/C++ CI 
#events to run the CI 
on:
  push:
    branches:
    - master
    - remotes/origin/Tom-Leung-1
  pull_request:
    branches:  
    - master
    - remotes/origin/Tom-Leung-1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run code.c
    - run: gcc code.c -o code; ./code
